<!DOCTYPE html>
<html>
<head>
    <title>Product Inventory Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4CAF50;
            padding-bottom: 10px;
        }
        .header h2 {
            margin: 0;
            color: #2E7D32;
            text-transform: uppercase;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
        }
        .info-bar {
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
        }
        .info-bar div {
            font-size: 11px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f2f2f2;
            color: #333;
            font-weight: bold;
            text-align: left;
            padding: 10px;
            border: 1px solid #ddd;
        }
        td {
            padding: 10px;
            border: 1px solid #ddd;
            vertical-align: top;
        }
        .status-badge {
            padding: 3px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
        }
        .status-in-stock { background-color: #C8E6C9; color: #2E7D32; }
        .status-low-stock { background-color: #FFF9C4; color: #FBC02D; }
        .status-critical { background-color: #FFEBEE; color: #C62828; }
        .status-out-of-stock { background-color: #E0E0E0; color: #616161; }
        
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }
        .page-number:before {
            content: "Page " counter(page);
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Product Inventory Report</h2>
        <p>{{ auth()->user()->leadFarmer->group_name ?? 'Lead Farmer Group' }} Inventory</p>
    </div>

    <div class="info-bar">
        <div><strong>Generated Date:</strong> {{ date('d M Y H:i') }}</div>
        <div><strong>Generated By:</strong> {{ auth()->user()->username }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Farmer</th>
                <th>Category</th>
                <th style="text-align: right;">Quantity</th>
                <th style="text-align: right;">Capacity</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $product)
            @php
                $status = $product->inventory_status;
                $statusClass = 'status-' . strtolower(str_replace(' ', '-', $status));
            @endphp
            <tr>
                <td><strong>{{ $product->product_name }}</strong></td>
                <td>{{ $product->farmer->name ?? 'N/A' }}</td>
                <td>{{ $product->category->category_name ?? 'N/A' }}</td>
                <td style="text-align: right;">{{ number_format($product->quantity, 2) }} {{ $product->unit_of_measure }}</td>
                <td style="text-align: right;">{{ number_format($product->stock_capacity, 2) }} {{ $product->unit_of_measure }}</td>
                <td>
                    <span class="status-badge {{ $statusClass }}">
                        {{ $status }}
                    </span>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <div>&copy; {{ date('Y') }} GreenMarket CSIAP. All rights reserved.</div>
        <div class="page-number"></div>
    </div>
</body>
</html>
